---
rust:
  directory: .
  manifestPath: rust/Cargo.toml

# This has been made to allow compilation with -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON
#Â Once the new Uniffi version 0.30.0, which supports this flag, is released, we will be able to remove it.
noOverwrite:
  - "android/build.gradle"
