[workspace]
resolver = "2"
members = [
    "lzy",
    "cojson-core",
    "cojson-core-wasm",
    "cojson-core-napi",
    "cojson-core-rn/rust",
    "bf-tree-web"
]

[workspace.dependencies]
uniffi = "0.29"
